### ISSUE TITLE
Kinect transform from color to depth

### ISSUE THREAD

**Issue by mmalmeid** [mgaoling/mpl_calibration_toolbox#10]
Hi,

I started using your dataset, but it just dawned on me that the [calibration page](https://star-datasets.github.io/vector/calibration/) does not contain the extrinsic calibration from the kinect color camera to depth camera.
As I understood from the [paper](https://star-datasets.github.io/vector/assets/pdf/VECtor.pdf) and the [calibration page](https://star-datasets.github.io/vector/calibration/), the transform from the kinect's color camera to depth camera is calibrated from factory, and hence it was not calibrated in any of your pipelines.
However, I cannot find that transform anywhere. I know I could use a nominal value for that transform, but I'm wondering if it would be possible to share the factory-calibrated transform for the specific device that was used to collect the VECtor data.

Would it be possible to share that calibration file? That would be greatly appreciated.

**Comment by mmalmeid** [comment]
Nevermind, the transform can be found here: https://star-datasets.github.io/vector/assets/yaml/rgbd_camera_calibrated_extrinsic_results.yaml

**Comment by mgaoling** [comment]
Note that the link you posted here is not from factory, but calibration results from us.
