### ISSUE TITLE
T_B_C matrix  for event cameras and RGBD camera

### ISSUE THREAD

**Issue by msh003** [mgaoling/mpl_calibration_toolbox#2]
Hello,

I hope this message finds you well. I wanted to express my gratitude for providing the VECtor Dataset and the associated tools. They have proven to be invaluable for my work.
I am currently utilizing the dataset to evaluate and fine-tune an algorithm. However, to proceed effectively, I require access to a critical component: T_B_C matrix , which represents the Translation from Camera Sensor to Lens Entrance Pupil. This transformation matrix is crucial as it specifies the translation in 3D space from the camera's image sensor (C) to the camera's lens entrance pupil (B).
Unfortunately, I couldn't locate this matrix within your camera calibration resources. It would greatly assist my efforts if you could provide me with the matrix or direct me to the video or documentation used for your camera calibration.
I truly appreciate your assistance in this matter and thank you in advance for your time and response.

**Comment by mgaoling** [comment]
May I ask why this matters to your task, and how should you usually calibrate such a transformation matrix?

**Comment by msh003** [comment]
Thank you so much for your response. I want to implement [rpg_ultimate_slam_open](https://github.com/uzh-rpg/rpg_ultimate_slam_open) on your data set. In the [calibration part](https://github.com/uzh-rpg/rpg_ultimate_slam_open/blob/main/calibration/DAVIS-example.yaml), I need to know T_B_C matrix.

**Comment by mgaoling** [comment]
I guess it‘s the IMU to camera transformation.

**Comment by msh003** [comment]
Thank you so much for your help and clarification.
