### ISSUE TITLE
about focal length

### ISSUE THREAD

**Issue by xingyi5166** [mgaoling/mpl_calibration_toolbox#3]
Hi, May I ask what is the focal length (f in pixels, not f_x or f_y), and baseline length (in meters) of your regular camera? Thanks!

**Comment by mgaoling** [comment]
While I'm not sure about the particular camera you're talking about, you can find out more information on this [page](https://star-datasets.github.io/vector/about/sensor/). Simply select the sensor/lens you'd like to learn more about.

Regarding the focal length in pixels, I suggest examining the intrinsic calibration results, i.e. the K matrix.

**Comment by xingyi5166** [comment]
> While I'm not sure about the particular camera you're talking about, you can find out more information on this [page](https://star-datasets.github.io/vector/about/sensor/). Simply select the sensor/lens you'd like to learn more about.
> 
> Regarding the focal length in pixels, I suggest examining the intrinsic calibration results, i.e. the K matrix.

Sorry for the confusion! Regarding the stereo camera [https://star-datasets.github.io/vector/assets/yaml/left_regular_camera_intrinsic_results.yaml](url) and [https://star-datasets.github.io/vector/assets/yaml/right_regular_camera_intrinsic_results.yaml](url), could you give some details for the baseline length?

**Comment by mgaoling** [comment]
Please refer to [this page](https://www.flir.com/products/grasshopper3-usb3/?model=GS3-U3-51S5C-C) and [this page](https://lenses.kowa-usa.com/jc-series/479-lm6jc.html).

**Comment by xingyi5166** [comment]
Thanks

> Please refer to [this page](https://www.flir.com/products/grasshopper3-usb3/?model=GS3-U3-51S5C-C) and [this page](https://lenses.kowa-usa.com/jc-series/479-lm6jc.html).

Thanks for your more details! The baseline is the distance between two stereo cameras. May I ask how to get the transformation matrix from those two cameras?

**Comment by mgaoling** [comment]
The baseline is about 17cm. You can find the transformation in the Joint Camera Extrinsic Calibration section under the [calibration page](https://star-datasets.github.io/vector/calibration/).
