### ISSUE TITLE
about ground truth trajectory 

### ISSUE THREAD

**Issue by xingyi5166** [mgaoling/mpl_calibration_toolbox#4]
Hi,

I tried to use the trajectory from https://star-datasets.github.io/vector/download/ (sofa-normal txt file) to reconstruct the whole scene. It looks the camera is not on the right track. Is there any preprocesses necessary? For example, I encounter one dataset needs to apply a rotation transformation before reconstructing the 3D scene. Thanks!

**Comment by mgaoling** [comment]
You need to transform the ground truth poses from the lidar frame to the camera frame. You can find such a transformation in the extrinsic calibration files.

**Comment by xingyi5166** [comment]
> You need to transform the ground truth poses from the lidar frame to the camera frame. You can find such a transformation in the extrinsic calibration files.

Thanks for your reply! Do you have an example to show?
