### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by jiheddachraoui** [mgaoling/mpl_calibration_toolbox#7]
Hello, during installation I encountered an error while attempting to build the project using catkin_make. The error message is as follows:
```
/home/litis/calibration_ws/src/mpl_calibration_toolbox/src/joint_extrinsic_calibrator.cpp:143:52: error: expected type-specifier
  143 |     problem.AddParameterBlock(param_q_cr_b, 4, new ceres::QuaternionParameterization());
      |                                                    ^~~~~
/home/litis/calibration_ws/src/mpl_calibration_toolbox/src/joint_extrinsic_calibrator.cpp:153:53: error: expected type-specifier
  153 |     problem.AddParameterBlock(param_q_cx_cr, 4, new ceres::QuaternionParameterization());
      |                                                     ^~~~~
make[2]: *** [mpl_calibration_toolbox/CMakeFiles/joint_extrinsic_calibrator.dir/build.make:63: mpl_calibration_toolbox/CMakeFiles/joint_extrinsic_calibrator.dir/src/joint_extrinsic_calibrator.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:557: mpl_calibration_toolbox/CMakeFiles/joint_extrinsic_calibrator.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Invoking "make -j20 -l20" failed
```

**Comment by mgaoling** [comment]
It's probably because of your ceres installation. What system are you using and how did you install ceres?

**Comment by jiheddachraoui** [comment]
I am currently utilizing Ubuntu 20.04, and I obtained Ceres Solver version 2.2.0 by following the installation instructions provided on this website: http://ceres-solver.org/installation.html

**Comment by mgaoling** [comment]
Better to use apt to install the ceres library as instructed in the README.

Which calibration functionality do you need for your task? If it is not the joint extrinsic calibration, then simply commenting out Line 40 and 44 in the CMakeLists should suffice.

**Comment by jiheddachraoui** [comment]
My application incorporates the calibration of multiple sensors camera Lidar , IMU ......

**Comment by mgaoling** [comment]
It is recommended to use the Ceres Solver version 1.14.0.

Nonetheless, for those opting for a more recent version, you could manually modify the class name within the file _src/joint_extrinsic_calibrator.cpp_:

At line 143 & 153, change `new ceres::QuaternionParameterization()` to `ceres::QuaternionManifold()`.
